# Generated by Django 4.1.1 on 2022-10-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_basemodel_name"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Zone", new_name="Corridor",),
        migrations.RenameField(
            model_name="municipality", old_name="zones", new_name="corridors",
        ),
    ]
