# Generated by Django 4.1.1 on 2022-11-09 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('type', models.CharField(choices=[('INT', 'Interior'), ('EXT', 'Exterior')], default='INT', max_length=100, verbose_name='Type')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='EquipmentQuantity',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractmodel')),
                ('quantity', models.IntegerField(null=True, verbose_name='Equipment quantity per prototype')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.equipment')),
            ],
            bases=('core.abstractmodel',),
        ),
        migrations.CreateModel(
            name='Finishing',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('total_units', models.IntegerField(null=True, verbose_name='Total units')),
                ('m2_terrain', models.FloatField(null=True, verbose_name='Terrain in square meters')),
                ('m2_constructed', models.FloatField(null=True, verbose_name='Constructed area in square meters')),
                ('m2_habitable', models.FloatField(null=True, verbose_name='Habiable area in square meters')),
                ('floors', models.SmallIntegerField(default=1, null=True, verbose_name='Pisos')),
                ('equipments', models.ManyToManyField(null=True, through='prototype.EquipmentQuantity', to='prototype.equipment')),
                ('project_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('propertyType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prototype.propertytype')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Triangulo',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractmodel')),
                ('finishings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.finishing')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.material')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.prototype')),
            ],
            bases=('core.abstractmodel',),
        ),
        migrations.AddField(
            model_name='prototype',
            name='segment_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.segment'),
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('price', models.IntegerField(null=True, verbose_name='Price')),
                ('available_units', models.IntegerField(null=True, verbose_name='Available Units')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.prototype')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentquantity',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.prototype'),
        ),
        migrations.AddConstraint(
            model_name='triangulo',
            constraint=models.UniqueConstraint(fields=('finishings', 'material', 'prototype'), name='Unique triangles'),
        ),
    ]
