# Generated by Django 4.1.1 on 2022-10-13 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('type', models.CharField(choices=[('INT', 'Interior'), ('EXT', 'Exterior')], default='INT', max_length=100, verbose_name='Type')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Finishing',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('total_units', models.IntegerField(verbose_name='Total units')),
                ('sold_units', models.IntegerField(verbose_name='Sold units')),
                ('m2_terrain', models.FloatField(verbose_name='Terrain in square meters')),
                ('m2_constructed', models.FloatField(verbose_name='Constructed area in square meters')),
                ('m2_habitable', models.FloatField(verbose_name='Habiable area in square meters')),
                ('equipments', models.ManyToManyField(to='prototype.equipment')),
                ('finishings', models.ManyToManyField(to='prototype.finishing')),
                ('project_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
                ('propertyType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.propertytype')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractmodel')),
                ('type', models.CharField(choices=[('S', 'Sell'), ('D', 'Refund')], default='S', max_length=100, verbose_name='Type')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.prototype')),
            ],
            bases=('core.abstractmodel',),
        ),
        migrations.AddField(
            model_name='prototype',
            name='segment_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.segment'),
        ),
    ]
