# Generated by Django 4.1.1 on 2022-11-03 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('price', models.IntegerField(null=True, verbose_name='Price')),
                ('available_units', models.IntegerField(null=True, verbose_name='Available Units')),
            ],
        ),
        migrations.CreateModel(
            name='Triangulo',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractmodel')),
            ],
            bases=('core.abstractmodel',),
        ),
        migrations.RemoveField(
            model_name='finishing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='finishing',
            name='finishing_type',
        ),
        migrations.RemoveField(
            model_name='prototype',
            name='finishings',
        ),
        migrations.RemoveField(
            model_name='prototype',
            name='price',
        ),
        migrations.RemoveField(
            model_name='prototype',
            name='sold_units',
        ),
        migrations.RenameModel(
            old_name='FinishingType',
            new_name='Material',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='triangulo',
            name='finishings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.finishing'),
        ),
        migrations.AddField(
            model_name='triangulo',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.material'),
        ),
        migrations.AddField(
            model_name='triangulo',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.prototype'),
        ),
        migrations.AddField(
            model_name='historical',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prototype.prototype'),
        ),
    ]
