# Generated by Django 4.1.1 on 2022-11-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_historical_triangulo_remove_finishing_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='triangulo',
            constraint=models.UniqueConstraint(fields=('finishings', 'material', 'prototype'), name='Unique triangles'),
        ),
    ]
