# Generated by Django 4.1.1 on 2022-10-16 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prototype", "0002_prototype_floors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prototype",
            name="equipments",
            field=models.ManyToManyField(null=True, to="prototype.equipment"),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="finishings",
            field=models.ManyToManyField(null=True, to="prototype.finishing"),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="floors",
            field=models.SmallIntegerField(default=1, null=True, verbose_name="Pisos"),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="m2_constructed",
            field=models.FloatField(
                null=True, verbose_name="Constructed area in square meters"
            ),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="m2_habitable",
            field=models.FloatField(
                null=True, verbose_name="Habiable area in square meters"
            ),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="m2_terrain",
            field=models.FloatField(null=True, verbose_name="Terrain in square meters"),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="price",
            field=models.IntegerField(null=True, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="propertyType",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="prototype.propertytype",
            ),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="sold_units",
            field=models.IntegerField(null=True, verbose_name="Sold units"),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="total_units",
            field=models.IntegerField(null=True, verbose_name="Total units"),
        ),
    ]
