# Generated by Django 4.1.1 on 2022-11-04 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_triangulo_unique triangles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
