# Generated by Django 4.1.1 on 2022-10-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_basemodel_name"),
        ("prototype", "0003_alter_prototype_equipments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinishingType",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
