# Generated by Django 4.1.1 on 2022-10-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
