# Generated by Django 4.1.1 on 2022-12-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_project_levels_project_levels_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="social_networks",
            field=models.CharField(max_length=200, verbose_name="Social networks"),
        ),
    ]
