# Generated by Django 4.1.1 on 2022-12-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_social_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='social_networks',
            field=models.TextField(verbose_name='Social networks'),
        ),
        migrations.AlterField(
            model_name='project',
            name='social_networks',
            field=models.TextField(verbose_name='Social networks'),
        ),
    ]
